name       : gcolor3
version    : 2.1
release    : 1
source     :
    - https://github.com/Unia/gcolor3/archive/v2.1.tar.gz : b7f65c0a44eb52622bf59bd04c15f01e05414167d86c3862863c0f91da60dab9
license    : GPL-2.0
summary    : simple color chooser
description: |
    A simple color chooser written in GTK3 (like gcolor2)
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gnome-common
patterns   :
    - /usr/share/man
setup      : |
    ./autogen.sh $CONFOPTS
build      : |
    %make
install    : |
    %make_install

