name       : gcolor3
version    : 2.3.1
release    : 5
source     :
    - https://github.com/Hjdskes/gcolor3/archive/v2.3.1.tar.gz : eba71211fa023b9ddd6865930b24f6954f50157cf147ba950bf27c0c03304a0b
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Simple color chooser
description: |
    A simple color chooser written in GTK3 (like gcolor2)
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gnome-common
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
