name       : gcolor3
version    : 2.2
release    : 3
source     :
    - https://github.com/Hjdskes/gcolor3/archive/v2.2.tar.gz : a3f67108ef7524b424b774b4b68332e45371703f61d659ce7ca1da47c7fb5590
license    : GPL-2.0
component  : multimedia.graphics
summary    : Simple color chooser
description: |
    A simple color chooser written in GTK3 (like gcolor2)
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gnome-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
